//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WineExhibitionQuestionnaire.Resources.LocRes", typeof(LocRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Answer_No {
            get {
                return ResourceManager.GetString("Answer_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, with the same stand in roughly the same place.
        /// </summary>
        public static string Answer_Yes {
            get {
                return ResourceManager.GetString("Answer_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, with a different stand of size:.
        /// </summary>
        public static string Answer_Yes_But {
            get {
                return ResourceManager.GetString("Answer_Yes_But", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Austria.
        /// </summary>
        public static string AT {
            get {
                return ResourceManager.GetString("AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: 18th-20th February 2022.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany.
        /// </summary>
        public static string DE {
            get {
                return ResourceManager.GetString("DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participation &quot;Weinmesse 2022&quot;.
        /// </summary>
        public static string Email_Title {
            get {
                return ResourceManager.GetString("Email_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to fill out the captcha..
        /// </summary>
        public static string Error_Captcha_01 {
            get {
                return ResourceManager.GetString("Error_Captcha_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong captcha answer..
        /// </summary>
        public static string Error_Captcha_02 {
            get {
                return ResourceManager.GetString("Error_Captcha_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Data.
        /// </summary>
        public static string Index_Contact {
            get {
                return ResourceManager.GetString("Index_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression of interest for participation at the &quot;Weinmesse 2022&quot;.
        /// </summary>
        public static string Index_Header {
            get {
                return ResourceManager.GetString("Index_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit order.
        /// </summary>
        public static string Index_Submit {
            get {
                return ResourceManager.GetString("Index_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Invoice_Amount {
            get {
                return ResourceManager.GetString("Invoice_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.pdf.
        /// </summary>
        public static string Invoice_Filename {
            get {
                return ResourceManager.GetString("Invoice_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        public static string Invoice_ObjectNumber {
            get {
                return ResourceManager.GetString("Invoice_ObjectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice for Winebox.
        /// </summary>
        public static string Invoice_Paragraph {
            get {
                return ResourceManager.GetString("Invoice_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Invoice_Price {
            get {
                return ResourceManager.GetString("Invoice_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Per Unit.
        /// </summary>
        public static string Invoice_Price_Unit {
            get {
                return ResourceManager.GetString("Invoice_Price_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        public static string Invoice_Shipping {
            get {
                return ResourceManager.GetString("Invoice_Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please transfer the total amount of {0} € to the following account and state the order number {1} as the purpose. {2}.
        /// </summary>
        public static string Invoice_Transferral_Text {
            get {
                return ResourceManager.GetString("Invoice_Transferral_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to won&apos;t.
        /// </summary>
        public static string Not {
            get {
                return ResourceManager.GetString("Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Number.
        /// </summary>
        public static string Nr {
            get {
                return ResourceManager.GetString("Nr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to participate.
        /// </summary>
        public static string Participate {
            get {
                return ResourceManager.GetString("Participate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for submitting your information.
        /// </summary>
        public static string Success_Header {
            get {
                return ResourceManager.GetString("Success_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You{0] take part at the &quot;Weinmesse&quot; from 18.-20. February 2022..
        /// </summary>
        public static string Success_Participate {
            get {
                return ResourceManager.GetString("Success_Participate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to similar to the stand of the last participation.
        /// </summary>
        public static string Success_Similar {
            get {
                return ResourceManager.GetString("Success_Similar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your stand: {0}..
        /// </summary>
        public static string Success_Size {
            get {
                return ResourceManager.GetString("Success_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data:.
        /// </summary>
        public static string Success_Text {
            get {
                return ResourceManager.GetString("Success_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        public static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
    }
}
