USE [WineExhibitionQuestionnaire]
GO

/****** Object:  Table [dbo].[CLIENT_DATA]    Script Date: 6/4/2021 3:09:49 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLIENT_DATA](
	[ID] [uniqueidentifier] NOT NULL,
	[COMPANY_NAME] [nvarchar](255) NOT NULL,
	[FIRST_NAME] [nvarchar](255) NOT NULL,
	[LAST_NAME] [nvarchar](255) NOT NULL,
	[EMAIL] [nvarchar](255) NOT NULL,
	[PARTICIPATE] [tinyint] NOT NULL,
	[STAND_SIZE] [int] NULL,
	[CREATED_AT] [datetime] NOT NULL,
 CONSTRAINT [PK_CLIENT_DATA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


